apiVersion: apps/v1
kind: Deployment
metadata:
  name: ourstore-backend
  labels:
    app: ourstore-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ourstore-backend
  template:
    metadata:
      labels:
        app: ourstore-backend
    spec:
      containers:
        - name: ourstore-backend
          image: shaiksameer3909/ourstore-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8089
          env:
            - name: SERVER_PORT
              value: "8081"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: ourstore-config
                  key: spring.datasource.url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ourstore-db-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ourstore-db-secret
                  key: password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: ourstore-backend
spec:
  selector:
    app: ourstore-backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001
