apiVersion: v1
kind: ConfigMap
metadata:
  name: ourstore-config
data:
  spring.datasource.url: jdbc:mysql://mysql:3306/ourstore?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
---
apiVersion: v1
kind: Secret
metadata:
  name: ourstore-db-secret
type: Opaque
stringData:
  username: root
  password: shaik
