apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ourstore-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: ourstore.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ourstore-backend
                port:
                  number: 8081
